"Name: NPC Tù Céng Full Skill ID: 1802 Script: \script\global\vldoxanh\npc\npccongfullskill.lua DropFile:  Life: 100 NguHanh: 0 Kind: 3"
"Name: §¹i L·o S­ ID: 1877 Script: \script\global\vldoxanh\upgradegoldhorse\main.lua DropFile:  Life: 100 NguHanh: 2 Kind: 3"
"Name: Éò¾Å ID: 323 Script: \script\Á½ºşÇø\°ÍÁêÏØ\npc\°ÍÁêÏØ_Â·ÈË10ÉÌÈË¶Ô»°.lua DropFile:  Life: 100 NguHanh: 0 Kind: 3"
"Name: ÎâÉñÒ½ ID: 389 Script: \script\Á½ºşÇø\°ÍÁêÏØ\npc\°ÍÁêÏØ_Ò©µêÀÏ°å¶Ô»°.lua DropFile:  Life: 100 NguHanh: 0 Kind: 3"
"Name: ÌìÍõ½«Áì ID: 184 Script: \script\Á½ºşÇø\°ÍÁêÏØ\npc\°ÍÁêÏØ_ÌìÍõ°ïÖÚ¶Ô»°.lua DropFile: \settings\item\npcdroprate.ini Life: 100 NguHanh: 0 Kind: 3"
"Name: ÌìÍõ½«Áì ID: 184 Script: \script\Á½ºşÇø\°ÍÁêÏØ\npc\°ÍÁêÏØ_ÌìÍõ°ïÖÚ¶Ô»°.lua DropFile: \settings\item\npcdroprate.ini Life: 100 NguHanh: 0 Kind: 3"
"Name: Hç Trî T©n Thñ ID: 1867 Script: \script\global\vldoxanh\hotrotanthu\hotropgaming.lua DropFile:  Life: 100 NguHanh: 2 Kind: 3"
"Name: Ìú½³ ID: 198 Script: \script\ÖĞÔ­ÄÏÇø\ÏåÑô\ÏåÑô\npc\ÏåÑô_Ìú½³¶Ô»°.lua DropFile:  Life: 100 NguHanh: 0 Kind: 3"
"Name: Ò°ÛÅ ID: 108 Script: \script\global\seasonnpc.lua DropFile: \settings\item\npcdroprate.ini Life: 100 NguHanh: 0 Kind: 3"
"Name: Ìú½³Ñ§Í½ ID: 200 Script: \script\Î÷ÄÏ±±Çø\³É¶¼\³É¶¼\Ö°ÄÜnpc\Î÷ÄÏ±±Çø-³É¶¼¸®--Ìú½³Ñ§Í½¶Ô»°.lua DropFile:  Life: 100 NguHanh: 0 Kind: 3"
"Name: ³µ·ò ID: 238 Script: \script\Î÷ÄÏ±±Çø\³É¶¼\³É¶¼\Ö°ÄÜnpc\Î÷ÄÏ±±Çø-³É¶¼¸®--æäÕ¾³µ·ò¶Ô»°.lua DropFile:  Life: 100 NguHanh: 0 Kind: 3"
